{% set name = "podaac-data-subscriber" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e31671f88c53be356e9364cea7fd311bae6bc309813d0b3e4349f7b84f47728f

build:
  entry_points:
    - podaac-data-subscriber = subscriber.podaac_data_subscriber:run
    - podaac-data-downloader = subscriber.podaac_data_downloader:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6
    - packaging
    - requests
    - tenacity

test:
  imports:
    - subscriber
  commands:
    - pip check
    - podaac-data-subscriber -h
    - podaac-data-downloader -h
  requires:
    - pip

about:
  home: https://github.com/podaac/data-subscriber
  summary: PO.DAAC Data Susbcriber Command Line Tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
